# Generated by Django 4.2.16 on 2024-11-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='user1731727148557', max_length=255),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
