# Generated by Django 4.2.16 on 2024-11-16 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user/profile.png', upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='user1731771737131', max_length=255),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
