# Generated by Django 4.2.16 on 2024-11-17 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_book_file_alter_book_genre_alter_user_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='user1731808169904', max_length=255),
        ),
    ]
